version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-sample-resizeImgWithEdge"
# sam deployコマンドに "--resolve-s3" オプションをつけない場合は下の"s3_bucket"の設定が必要です（ビルド成果物をアップロードするバケット名を指定します）
# s3_bucket = "YOUR_TEMP_BUCKT"
s3_prefix = "sam-sample-resizeImgWithEdge"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "OriginS3BucketName=XXXXXX OriginS3BucketCreation=false"
image_repositories = []
